# Warning: this name must stay in sync with the badges referenced in the README
name: 'tests MSVC'

on:
  push:
    branches:
      - 'main'
  pull_request:
  schedule:
      - cron: "0 0 * * 6"  # Run every Saturday at midnight

jobs:
  msvc:

    runs-on: windows-latest
    env:
        VULKAN_SDK_VERSION: 1.3.243.0
    strategy:
      matrix:
        include:
          - build_backend: ninja
          - build_backend: vs

    defaults:
      run:
        shell: pwsh

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Build (${{matrix.build_backend}})
        run: |
          .\scripts\msvc-env.ps1
          python.exe .\configure.py --debug-opts gpu_capture --build-backend ${{matrix.build_backend}}
          nmake

      - name: Python import and dylib runtime test
        run: |
          .\venv\Scripts\Activate.ps1
          for ($i = 0; $i -lt 15; $i++) {
            python.exe -c "import pynopegl, pynopegl_utils"
            if ($? -eq 0) {
              "Successfully imported"
              break;
            }
            "Import {0} failed" -f $i
            Start-Sleep -Seconds 1
          }
          ngl-python.exe -h
